# Render configuration for backend
version: 1
build:
  commands:
    - cd backend
    - npm install
start:
  command: cd backend && npm start
env:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: 3001
